# vim: ai:ts=2:sw=2:et
version: "3"
networks: {}
volumes:
  db-data:
  db-logs:
  es-data:
  web-logs:

services:
  console:
    image: eu.gcr.io/aequalis-io/php-image
    user: "${CUID}:${CGID}"
    links:
      - db
      - elasticsearch
      - mailcatch
    network_mode: bridge
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - XDEBUG_CONFIG
      - DATABASE_URL
      - MAGEMENT_ENV
      - MAGEMENT_SECRET
      - MYSQL_ROOT_PASSWORD
      - "HOME=${CHOME}"
      - SSH_AUTH_SOCK
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}:rw"
      - "${HOME}:${CHOME}"
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
      - "${GIT_CONFIG_LOCAL}:/etc/gitconfig:ro"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  dashboard:
    image: eu.gcr.io/aequalis-io/magement-dashboard
    links:
      - web
      - elasticsearch
    ports:
      - "${DASHBOARD_PORT}:80"
    network_mode: bridge

  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    network_mode: bridge
    volumes:
      - db-data:/var/lib/mysql:rw
      - db-logs:/var/logs/mysql:rw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    network_mode: bridge
    environment:
      - ELASTICSEARCH_PASSWORD
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw

  filebeat:
    image: eu.gcr.io/aequalis-io/filebeat-image
    network_mode: bridge
    command: filebeat -e -strict.perms=false
    environment:
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - KIBANA_HOST=kibana
    links:
      - db
      - elasticsearch
      - logstash
      - web
      - worker
    volumes:
      - ./var/log:/usr/share/filebeat/data/app-logs:ro
      - db-logs:/usr/share/filebeat/data/db-logs:ro
      - web-logs:/usr/share/filebeat/data/web-logs:ro

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    links:
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:5601"
    network_mode: bridge
    environment:
      ELASTIC_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: "${ELASTICSEARCH_INSTANCE_URL}"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    links:
      - elasticsearch
    network_mode: bridge
    environment:
      ES_URL: "${ELASTICSEARCH_NODES_URL}"
      ELASTIC_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  mailcatch:
    image: mailhog/mailhog
    network_mode: bridge

  web:
    image: eu.gcr.io/aequalis-io/nginx-image
    links:
      - mailcatch
      - worker
    network_mode: bridge
    ports:
      - "${MAGEMENT_PORT}:80"
    environment:
      - PHP_FPM_HOST=worker:9000
    working_dir: "${PWD}/web"
    volumes:
      - "${PWD}/web:${PWD}/web:ro"
      - web-logs:/var/log/nginx:rw

  worker:
    image: eu.gcr.io/aequalis-io/php-fpm-image
    user: "${CUID}:${CGID}"
    links:
      - db
      - elasticsearch
      - mailcatch
    network_mode: bridge
    environment:
      - XDEBUG_CONFIG
      - DATABASE_URL
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - MAGEMENT_ENV
      - MAGEMENT_SECRET
      - PHP_EXTRA_CONFIGURE_ARGS
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}:rw"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
