# vim: ai:ts=2:sw=2:et
version: "3"
networks: {}
volumes:
  db-data:
  db-logs:
  web-logs:

services:
  amqp:
    image: rabbitmq:3.8-alpine
    network_mode: bridge
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

  console:
    image: magento-2-php-local:latest
    user: "${UID}:${GID}"
    links:
      - db
      - mailcatch
      - redis
      - varnish
    ports:
      - "${XDEBUG_PORT_CONSOLE}:9001"
    network_mode: bridge
    environment:
      - CONFIG__DEFAULT__WEB__UNSECURE__BASE_URL
      - CONFIG__DEFAULT__WEB__SECURE__BASE_URL
      - BACKEND__FRONT_NAME
      - CRYPT__KEY
      - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__HOST
      - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__PORT
      - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__PASSWORD
      - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__DATABASE
      - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__HOST
      - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__PORT
      - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__PASSWORD
      - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__DATABASE
      - DB__CONNECTION__DEFAULT__HOST
      - DB__CONNECTION__DEFAULT__DBNAME
      - DB__CONNECTION__DEFAULT__USERNAME
      - DB__CONNECTION__DEFAULT__PASSWORD
      - DB__CONNECTION__INDEXER__HOST
      - DB__CONNECTION__INDEXER__DBNAME
      - DB__CONNECTION__INDEXER__USERNAME
      - DB__CONNECTION__INDEXER__PASSWORD
      - QUEUE__AMQP__HOST
      - QUEUE__AMQP__PORT
      - QUEUE__AMQP__USER
      - QUEUE__AMQP__PASSWORD
      - QUEUE__AMQP__VIRTUALHOST
      - SESSION__REDIS__HOST
      - SESSION__REDIS__PORT
      - SESSION__REDIS__PASSWORD
      - SESSION__REDIS__DATABASE
      - CONFIG__DEFAULT__ADMIN__SECURITY__USE_FORM_KEY
      - CONFIG__DEFAULT__ADMIN__SECURITY__ADMIN_ACCOUNT_SHARING
      - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__DATE_FIELDS_ORDER
      - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__TIME_FORMAT
      - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__USE_CALENDAR
      - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__YEAR_RANGE
      - CONFIG__DEFAULT__CATALOG__FRONTEND__FLAT_CATALOG_CATEGORY
      - CONFIG__DEFAULT__CATALOG__FRONTEND__FLAT_CATALOG_PRODUCT
      - CONFIG__DEFAULT__CMS__WYSIWYG__ENABLED
      - CONFIG__DEFAULT__CURRENCY__OPTIONS__ALLOW
      - CONFIG__DEFAULT__CURRENCY__OPTIONS__BASE
      - CONFIG__DEFAULT__CURRENCY__OPTIONS__DEFAULT
      - CONFIG__DEFAULT__DEV__CSS__MINIFY_FILES
      - CONFIG__DEFAULT__DEV__CSS__MERGE_CSS_FILES
      - CONFIG__DEFAULT__DEV__GRID__ASYNC_INDEXING
      - CONFIG__DEFAULT__DEV__JS__MERGE_FILES
      - CONFIG__DEFAULT__DEV__JS__MINIFY_FILES
      - CONFIG__DEFAULT__DEV__JS__MOVE_SCRIPT_TO_BOTTOM
      - CONFIG__DEFAULT__DEV__JS__ENABLE_JS_BUNDLING
      - CONFIG__DEFAULT__DEV__TEMPLATE__MINIFY_HTML
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__NAME
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__STREET_LINE1
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__STREET_LINE2
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__POSTCODE
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__CITY
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__PHONE
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__HOURS
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__MERCHANT_VAT_NUMBER
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__COUNTRY_ID
      - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__REGION_ID
      - CONFIG__DEFAULT__GENERAL__COUNTRY__ALLOW
      - CONFIG__DEFAULT__GENERAL__COUNTRY__DEFAULT
      - CONFIG__DEFAULT__GENERAL__LOCALE__CODE
      - CONFIG__DEFAULT__GENERAL__LOCALE__FIRSTDAY
      - CONFIG__DEFAULT__GENERAL__LOCALE__TIMEZONE
      - CONFIG__DEFAULT__GENERAL__LOCALE__WEIGHT_UNIT
      - CONFIG__DEFAULT__MEDIACT_LAYOUT_HANDLE_OPTIMIZER__GENERAL__ENABLE
      - CONFIG__DEFAULT__MULTISHIPPING__OPTIONS__CHECKOUT_MULTIPLE
      - CONFIG__DEFAULT__SALES_EMAIL__GENERAL__ASYNC_SENDING
      - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__WRAPPING_ALLOW_ORDER
      - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__WRAPPING_ALLOW_ITEMS
      - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__ALLOW_GIFT_RECEIPT
      - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__ALLOW_PRINTED_CARD
      - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__CACHING_APPLICATION
      - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__VARNISH__BACKEND_HOST
      - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__VARNISH__BACKEND_PORT
      - CONFIG__DEFAULT__TAX__DEFAULTS__COUNTRY
      - CONFIG__DEFAULT__WEB__SECURE__USE_IN_ADMINHTML
      - CONFIG__DEFAULT__WEB__SECURE__USE_IN_FRONTEND
      - CONFIG__DEFAULT__WEB__SEO__USE_REWRITES
      - CONFIG__DEFAULT__WEB__SESSION__USE_FRONTEND_SID
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
#      - ./app/etc/env.php:/var/www/html/app/etc/env.php:ro
      - "${COMPOSER_HOME_LOCAL}:${HOME}/.composer:rw"
      - "${GIT_CONFIG_LOCAL}:/etc/gitconfig:ro"
      - "${GIT_IGNORE_LOCAL}:${HOME}/.gitignore:ro"
      - "${SSH_LOCAL}:${HOME}/.ssh:ro"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    network_mode: bridge
    volumes:
      - db-data:/var/lib/mysql:rw
      - db-logs:/var/logs/mysql:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  mailcatch:
    image: mailhog/mailhog
    network_mode: bridge
    ports:
      - "${MAILHOG_PORT}:8025"

  redis:
    image: redis:5.0-alpine
    network_mode: bridge

  varnish:
    image: varnish:stable
    links:
      - web
    network_mode: bridge
    ports:
      - "${VARNISH_PORT}:80"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro

  web:
    image: magento-2-nginx-local:latest
    links:
      - mailcatch
      - worker
    network_mode: bridge
    ports:
      - "${WEB_PORT}:80"
    environment:
      - PHP_FPM_HOST=worker:9000
    volumes:
      - ./pub:/var/www/html/pub:ro
      - ./nginx.conf.sample:/var/www/html/nginx.conf.sample:ro
      - web-logs:/var/log/nginx:rw

  worker:
    image: magento-2-php-fpm-local:latest
    user: "${UID}:${GID}"
    links:
      - db
      - mailcatch
      - redis
    ports:
      - "${XDEBUG_PORT_WORKER}:9002"
    network_mode: bridge
    environment:
    - CONFIG__DEFAULT__WEB__UNSECURE__BASE_URL
    - CONFIG__DEFAULT__WEB__SECURE__BASE_URL
    - BACKEND__FRONT_NAME
    - CRYPT__KEY
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__HOST
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__PORT
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__PASSWORD
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__DATABASE
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__HOST
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__PORT
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__PASSWORD
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__DATABASE
    - DB__CONNECTION__DEFAULT__HOST
    - DB__CONNECTION__DEFAULT__DBNAME
    - DB__CONNECTION__DEFAULT__USERNAME
    - DB__CONNECTION__DEFAULT__PASSWORD
    - DB__CONNECTION__INDEXER__HOST
    - DB__CONNECTION__INDEXER__DBNAME
    - DB__CONNECTION__INDEXER__USERNAME
    - DB__CONNECTION__INDEXER__PASSWORD
    - QUEUE__AMQP__HOST
    - QUEUE__AMQP__PORT
    - QUEUE__AMQP__USER
    - QUEUE__AMQP__PASSWORD
    - QUEUE__AMQP__VIRTUALHOST
    - SESSION__REDIS__HOST
    - SESSION__REDIS__PORT
    - SESSION__REDIS__PASSWORD
    - SESSION__REDIS__DATABASE
    - CONFIG__DEFAULT__ADMIN__SECURITY__USE_FORM_KEY
    - CONFIG__DEFAULT__ADMIN__SECURITY__ADMIN_ACCOUNT_SHARING
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__DATE_FIELDS_ORDER
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__TIME_FORMAT
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__USE_CALENDAR
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__YEAR_RANGE
    - CONFIG__DEFAULT__CATALOG__FRONTEND__FLAT_CATALOG_CATEGORY
    - CONFIG__DEFAULT__CATALOG__FRONTEND__FLAT_CATALOG_PRODUCT
    - CONFIG__DEFAULT__CMS__WYSIWYG__ENABLED
    - CONFIG__DEFAULT__CURRENCY__OPTIONS__ALLOW
    - CONFIG__DEFAULT__CURRENCY__OPTIONS__BASE
    - CONFIG__DEFAULT__CURRENCY__OPTIONS__DEFAULT
    - CONFIG__DEFAULT__DEV__CSS__MINIFY_FILES
    - CONFIG__DEFAULT__DEV__CSS__MERGE_CSS_FILES
    - CONFIG__DEFAULT__DEV__GRID__ASYNC_INDEXING
    - CONFIG__DEFAULT__DEV__JS__MERGE_FILES
    - CONFIG__DEFAULT__DEV__JS__MINIFY_FILES
    - CONFIG__DEFAULT__DEV__JS__MOVE_SCRIPT_TO_BOTTOM
    - CONFIG__DEFAULT__DEV__JS__ENABLE_JS_BUNDLING
    - CONFIG__DEFAULT__DEV__TEMPLATE__MINIFY_HTML
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__NAME
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__STREET_LINE1
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__STREET_LINE2
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__POSTCODE
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__CITY
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__PHONE
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__HOURS
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__MERCHANT_VAT_NUMBER
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__COUNTRY_ID
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__REGION_ID
    - CONFIG__DEFAULT__GENERAL__COUNTRY__ALLOW
    - CONFIG__DEFAULT__GENERAL__COUNTRY__DEFAULT
    - CONFIG__DEFAULT__GENERAL__LOCALE__CODE
    - CONFIG__DEFAULT__GENERAL__LOCALE__FIRSTDAY
    - CONFIG__DEFAULT__GENERAL__LOCALE__TIMEZONE
    - CONFIG__DEFAULT__GENERAL__LOCALE__WEIGHT_UNIT
    - CONFIG__DEFAULT__MEDIACT_LAYOUT_HANDLE_OPTIMIZER__GENERAL__ENABLE
    - CONFIG__DEFAULT__MULTISHIPPING__OPTIONS__CHECKOUT_MULTIPLE
    - CONFIG__DEFAULT__SALES_EMAIL__GENERAL__ASYNC_SENDING
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__WRAPPING_ALLOW_ORDER
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__WRAPPING_ALLOW_ITEMS
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__ALLOW_GIFT_RECEIPT
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__ALLOW_PRINTED_CARD
    - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__CACHING_APPLICATION
    - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__VARNISH__BACKEND_HOST
    - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__VARNISH__BACKEND_PORT
    - CONFIG__DEFAULT__TAX__DEFAULTS__COUNTRY
    - CONFIG__DEFAULT__WEB__SECURE__USE_IN_ADMINHTML
    - CONFIG__DEFAULT__WEB__SECURE__USE_IN_FRONTEND
    - CONFIG__DEFAULT__WEB__SEO__USE_REWRITES
    - CONFIG__DEFAULT__WEB__SESSION__USE_FRONTEND_SID
    volumes:
      - ./:/var/www/html:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
