# vim: ai:ts=2:sw=2:et
version: "3.4"
networks: {}
volumes:
  db-data:
  db-logs:
  es-data:
  web-logs:

x-custom:
  environment: &env-vars
    # Environment settings
    - "HOME=${CHOME}"
    - COMPOSER_MEMORY_LIMIT
    # Database settings
    - DB_HOST
    - DB_USER
    - DB_PASS
    - DB_NAME
    - MYSQL_PORT
    # URL settings
    - CONFIG__DEFAULT__WEB__UNSECURE__BASE_URL
    - CONFIG__DEFAULT__WEB__SECURE__BASE_URL
    # GCP settings
    - CLOUDSDK_CONFIG=/config/mygcloud
    - GCLOUD_BUCKET_URL_DB
    - GCLOUD_BUCKET_URL_MEDIA
    # Magento settings
    - BACKEND__FRONT_NAME
    - CRYPT__KEY
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__HOST
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__PORT
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__PASSWORD
    - CACHE__FRONTEND__DEFAULT__BACKEND_OPTIONS__DATABASE
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__HOST
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__PORT
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__PASSWORD
    - CACHE__FRONTEND__PAGE_CACHE__BACKEND_OPTIONS__DATABASE
    - DB__CONNECTION__DEFAULT__HOST
    - DB__CONNECTION__DEFAULT__DBNAME
    - DB__CONNECTION__DEFAULT__USERNAME
    - DB__CONNECTION__DEFAULT__PASSWORD
    - DB__CONNECTION__INDEXER__HOST
    - DB__CONNECTION__INDEXER__DBNAME
    - DB__CONNECTION__INDEXER__USERNAME
    - DB__CONNECTION__INDEXER__PASSWORD
    - QUEUE__AMQP__HOST
    - QUEUE__AMQP__PORT
    - QUEUE__AMQP__USER
    - QUEUE__AMQP__PASSWORD
    - QUEUE__AMQP__VIRTUALHOST
    - SESSION__REDIS__HOST
    - SESSION__REDIS__PORT
    - SESSION__REDIS__PASSWORD
    - SESSION__REDIS__DATABASE
    - CONFIG__DEFAULT__ADMIN__SECURITY__USE_FORM_KEY
    - CONFIG__DEFAULT__ADMIN__SECURITY__ADMIN_ACCOUNT_SHARING
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__DATE_FIELDS_ORDER
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__TIME_FORMAT
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__USE_CALENDAR
    - CONFIG__DEFAULT__CATALOG__CUSTOM_OPTIONS__YEAR_RANGE
    - CONFIG__DEFAULT__CATALOG__FRONTEND__FLAT_CATALOG_CATEGORY
    - CONFIG__DEFAULT__CATALOG__FRONTEND__FLAT_CATALOG_PRODUCT
    - CONFIG__DEFAULT__CMS__WYSIWYG__ENABLED
    - CONFIG__DEFAULT__CATALOG__SEARCH__ENGINE
    - CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH6_SERVER_HOSTNAME
    - CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH6_SERVER_PORT
    - CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH6_ENABLE_AUTH
    - CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH6_USERNAME
    - CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH6_PASSWORD
    - CONFIG__DEFAULT__CURRENCY__OPTIONS__ALLOW
    - CONFIG__DEFAULT__CURRENCY__OPTIONS__BASE
    - CONFIG__DEFAULT__CURRENCY__OPTIONS__DEFAULT
    - CONFIG__DEFAULT__DEV__CSS__MINIFY_FILES
    - CONFIG__DEFAULT__DEV__CSS__MERGE_CSS_FILES
    - CONFIG__DEFAULT__DEV__GRID__ASYNC_INDEXING
    - CONFIG__DEFAULT__DEV__JS__MERGE_FILES
    - CONFIG__DEFAULT__DEV__JS__MINIFY_FILES
    - CONFIG__DEFAULT__DEV__JS__MOVE_SCRIPT_TO_BOTTOM
    - CONFIG__DEFAULT__DEV__JS__ENABLE_JS_BUNDLING
    - CONFIG__DEFAULT__DEV__STATIC__SIGN
    - CONFIG__DEFAULT__DEV__TEMPLATE__MINIFY_HTML
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__NAME
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__STREET_LINE1
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__STREET_LINE2
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__POSTCODE
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__CITY
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__PHONE
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__HOURS
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__MERCHANT_VAT_NUMBER
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__COUNTRY_ID
    - CONFIG__DEFAULT__GENERAL__STORE_INFORMATION__REGION_ID
    - CONFIG__DEFAULT__GENERAL__COUNTRY__ALLOW
    - CONFIG__DEFAULT__GENERAL__COUNTRY__DEFAULT
    - CONFIG__DEFAULT__GENERAL__LOCALE__CODE
    - CONFIG__DEFAULT__GENERAL__LOCALE__FIRSTDAY
    - CONFIG__DEFAULT__GENERAL__LOCALE__TIMEZONE
    - CONFIG__DEFAULT__GENERAL__LOCALE__WEIGHT_UNIT
    - CONFIG__DEFAULT__MEDIACT_LAYOUT_HANDLE_OPTIMIZER__GENERAL__ENABLE
    - CONFIG__DEFAULT__MULTISHIPPING__OPTIONS__CHECKOUT_MULTIPLE
    - CONFIG__DEFAULT__SALES_EMAIL__GENERAL__ASYNC_SENDING
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__WRAPPING_ALLOW_ORDER
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__WRAPPING_ALLOW_ITEMS
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__ALLOW_GIFT_RECEIPT
    - CONFIG__DEFAULT__SALES__GIFT_OPTIONS__ALLOW_PRINTED_CARD
    - CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__SERVERS
    - CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__ENABLE_HTTPS_MODE
    - CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__ENABLE_HTTP_AUTH
    - CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__HTTP_AUTH_USER
    - CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__HTTP_AUTH_PWD
    - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__CACHING_APPLICATION
    - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__VARNISH__BACKEND_HOST
    - CONFIG__DEFAULT__SYSTEM__FULL_PAGE_CACHE__VARNISH__BACKEND_PORT
    - CONFIG__DEFAULT__TAX__DEFAULTS__COUNTRY
    - CONFIG__DEFAULT__WEB__SECURE__USE_IN_ADMINHTML
    - CONFIG__DEFAULT__WEB__SECURE__USE_IN_FRONTEND
    - CONFIG__DEFAULT__WEB__SEO__USE_REWRITES
    - CONFIG__DEFAULT__WEB__SESSION__USE_FRONTEND_SID
    - MAGE_MODE

services:
  amqp:
    image: rabbitmq:3.8-alpine
    network_mode: bridge
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

  console:
    image: eu.gcr.io/mct-deployments/magento-2-console
    user: "${UID}:${GID}"
    links:
      - amqp
      - db
      - elasticsearch
      - mailcatch
      - redis
#      - varnish
    ports:
      - "${XDEBUG_PORT_CONSOLE}:9001"
    network_mode: bridge
    environment: *env-vars
    working_dir: "${PWD}"
    volumes:
      - "${HOME}:${CHOME}"
      - "${PWD}:${PWD}"
      - "${GCLOUD_LOCAL}:/config/mygcloud"
      - "${GIT_CONFIG_LOCAL}:/etc/gitconfig:ro"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    network_mode: bridge
    volumes:
      - db-data:/var/lib/mysql:rw
      - db-logs:/var/logs/mysql:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  elasticsearch:
    image: eu.gcr.io/mct-deployments/magento-2-elasticsearch
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    network_mode: bridge
    environment:
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_USERNAME
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw

  grunt:
    image: eu.gcr.io/mct-deployments/magento-2-console
    user: "${UID}:${GID}"
    links:
      - redis
    network_mode: bridge
    working_dir: "${PWD}"
    command: grunt-daemon
    environment: *env-vars
    volumes:
      - "${HOME}:${CHOME}"
      - "${PWD}:${PWD}"

  mailcatch:
    image: mailhog/mailhog
    network_mode: bridge
    ports:
      - "${MAILHOG_PORT}:8025"

  redis:
    image: redis:5.0-alpine
    network_mode: bridge

#  varnish:
#    image: emgag/varnish:5.2.1
#    links:
#      - web
#    network_mode: bridge
#    ports:
#      - "${VARNISH_PORT}:80"
#    volumes:
#      - ./default.vcl.dev:/etc/varnish/default.vcl:ro

  web:
    image: eu.gcr.io/mct-deployments/magento-2-nginx
    links:
      - worker
    network_mode: bridge
    ports:
      - "${WEB_PORT_HTTP}:80"
      - "${WEB_PORT_HTTPS}:443"
    environment:
      - PHP_FPM_HOST=worker:9000
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}:ro"
      - ./nginx-dev.conf:/etc/nginx/dev.conf:ro
      - web-logs:/var/log/nginx:rw

  worker:
    image: eu.gcr.io/mct-deployments/magento-2-php-fpm
    user: "${UID}:${GID}"
    links:
      - amqp
      - db
      - elasticsearch
      - mailcatch
      - redis
    ports:
      - "${XDEBUG_PORT_WORKER}:9002"
    network_mode: bridge
    environment: *env-vars
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}:rw"
      - "${PWD}/var/log:/var/log/:rw"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

