# vim: ai:ts=2:sw=2:et
version: "3.4"
networks:
  backend:
volumes:
  db-data:

x-custom:
  version: 1.2.0
  type: extended-php
  environment: &env-vars
    # Environment settings
    - COMPOSER_MEMORY_LIMIT=-1
    - "HOME=${CHOME}"
    - HTTPS=on
    - SSH_AUTH_SOCK
    - XDEBUG_CONFIG
    - COMPOSER_ALLOW_XDEBUG
    # Database settings
    - DB_HOST
    - DB_USER
    - DB_PASS
    - DB_NAME
    - MYSQL_PORT
    # GCP settings
    - CLOUDSDK_CONFIG=/config/mygcloud
    - GCLOUD_BUCKET_URL_DB
    - GCLOUD_BUCKET_URL_MEDIA

services:
  console:
    # TODO: replace by (more lightweight) image that is not dedicated to magento2
    image: "eu.gcr.io/mct-deployments/magento-2-console-php${PHP_VERSION}:latest"
    user: "${CUID}:${CGID}"
    links:
      - db
      - mailcatch
      - redis
    networks:
      - backend
    environment: *env-vars
    extra_hosts:
      - "${DNS_NAME}:${HOST_IP}"
    working_dir: "${PWD}"
    volumes:
      - "${HOME}:${CHOME}"
      - "${PWD}:${PWD}"
      - "${GCLOUD_LOCAL}:/config/mygcloud"
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  db:
    image: percona:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql:rw

  mailcatch:
    image: mailhog/mailhog
    networks:
      - backend
    ports:
      - "${MAILHOG_PORT}:8025"

  nginx-php-fpm:
    image: eu.gcr.io/mct-deployments/magento-2-nginx-php-fpm
    networks:
      - backend
    links:
      - php-fpm
    working_dir: "${PWD}"
    environment:
      - "MAGE_ROOT=${PWD}"
      - PHP_FPM_HOST
      - PHP_FPM_PORT
    extra_hosts:
      - "${DNS_NAME}:${HOST_IP}"
    volumes:
      - "${PWD}:${PWD}:ro"
      - ./nginx-dev.conf:/etc/nginx/app.conf:ro

  nginx-ssl-proxy:
    image: eu.gcr.io/mct-deployments/mediacthq-dev-nginx-ssl-proxy
    networks:
      - backend
    links:
      - nginx-php-fpm
    ports:
      - "${WEB_PORT_HTTP}:80"
      - "${WEB_PORT_HTTPS}:443"
    environment:
      - PROXY_HOST
      - PROXY_PORT
    working_dir: "${PWD}"

  php-fpm:
    image: "eu.gcr.io/mct-deployments/magento-2-php-fpm:${PHP_VERSION}"
    user: "${CUID}:${CGID}"
    networks:
      - backend
    links:
      - db
      - mailcatch
      - redis
    environment: *env-vars
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}:rw"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  redis:
    image: redis:6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend
